require 'pry'
# def name_mapping
#   missing_name_mapping = ["Wagner", "N Colorado", "Alabama St", "Albany NY", "Cent Arkansas", "Morgan St", "Robert Morris", "Gardner Webb", "Florida A&M", "Army", "Tulsa", "Grambling", "Illinois St", "Incarnate Word", "UT San Antonio", "Weber St", "SF Austin", "James Madison", "West Virginia", "Texas", "Howard", "Ark Pine Bluff", "Houston Bap", "Abilene Chr", "Idaho", "Norfolk St", "Colgate", "Bucknell", "E Washington", "VMI", "Rhode Island", "Ohio", "Portland St", "Monmouth NJ", "Northern Iowa", "Alcorn St", "Indiana St", "Sam Houston St", "ETSU", "Ball St", "Montana St", "Campbell", "LSU", "Georgia St", "Tennessee", "Southern Utah", "UC Davis", "Missouri", "Louisville"]

#   action_names = ["BYU Cougars", "Hawaii Warriors", "Connecticut Huskies", "Bowling Green Falcons", "Buffalo Bulls", "Western Kentucky Hilltoppers", "UCF Knights", "Charlotte 49ers", "Central Michigan Chippewas", "Clemson Tigers", "Tulane Green Wave", "Texas A&M Aggies", "Minnesota Golden Gophers", "Arizona State Sun Devils", "San Jose State Spartans", "Army Black Knights", "South Florida Bulls", "Michigan State Spartans", "Wake Forest Demon Deacons", "Nevada Wolf Pack", "Colorado Buffaloes", "North Carolina State Wolfpack", "Florida State Seminoles", "Illinois Fighting Illini", "Louisiana-Lafayette Ragin' Cajuns", "North Carolina Tar Heels", "Coastal Carolina Chanticleers", "Ball State Cardinals", "Memphis Tigers", "Kentucky Wildcats", "Iowa State Cyclones", "Ohio State Buckeyes", "Maryland Terrapins", "Nebraska Cornhuskers", "Kansas Jayhawks", "Ohio Bobcats", "West Virginia Mountaineers", "Washington Huskies", "Temple Owls", "Duke Blue Devils", "Boston College Eagles", "UTSA Roadrunners", "Liberty Flames", "Baylor Bears", "Air Force Falcons", "Appalachian State Mountaineers", "Navy Midshipmen", "Tennessee Volunteers", "Texas Tech Red Raiders", "Stanford Cardinal", "Arkansas Razorbacks", "New Mexico Lobos", "Troy Trojans", "California Bears", "Marshall Thundering Herd", "Western Michigan Broncos", "Kansas State Wildcats", "Southern Miss Golden Eagles", "Pittsburgh Panthers", "Vanderbilt Commodores", "LSU Tigers", "Wyoming Cowboys", "Iowa Hawkeyes", "Washington State Cougars", "Oklahoma Sooners", "Virginia Tech Hokies", "Northern Illinois Huskies", "Old Dominion Monarchs", "Oregon Ducks", "Michigan Wolverines", "North Texas Mean Green", "Texas Longhorns", "UTEP Miners", "Louisiana-Monroe Warhawks", "San Diego State Aztecs", "UNLV Rebels", "USC Trojans", "Miami (OH) RedHawks", "Toledo Rockets", "Purdue Boilermakers", "Massachusetts Minutemen", "TCU Horned Frogs", "Wisconsin Badgers", "Alabama Crimson Tide", "Georgia Southern Eagles", "Oregon State Beavers", "Rice Owls", "New Mexico State Aggies", "Notre Dame Fighting Irish", "Auburn Tigers", "Oklahoma State Cowboys", "South Carolina Gamecocks", "Utah State Aggies", "Louisville Cardinals", "Utah Utes", "Arizona Wildcats", "Florida Gators", "Cincinnati Bearcats", "Rutgers Scarlet Knights", "Penn State Nittany Lions", "Arkansas State Red Wolves", "Wagner Seahawks", "Morgan State Bears", "Robert Morris Colonials", "Central Arkansas Bears", "Florida A&M Rattlers", "Gardner-Webb Runnin' Bulldogs", "Albany Great Danes", "Georgia Tech Yellow Jackets", "Florida International Golden Panthers", "Texas State Bobcats", "South Dakota State Jackrabbits", "Kent State Golden Flashes", "Northern Colorado Bears", "Tulsa Golden Hurricane", "Colorado State Rams", "East Carolina Pirates", "Boise State Broncos", "Akron Zips", "Mississippi State Bulldogs", "Eastern Michigan Eagles", "Indiana Hoosiers", "Ole Miss Rebels", "Northern Iowa Panthers", "Florida Atlantic Owls", "Howard Bison", "South Alabama Jaguars", "Indiana State Sycamores", "Rhode Island Rams", "James Madison Dukes", "Eastern Washington Eagles", "Bucknell Bison", "Incarnate Word Cardinals", "Syracuse Orange", "Stephen F. Austin Lumberjacks", "Colgate Raiders", "East Tennessee State Buccaneers", "Holy Cross Crusaders", "Georgia State Panthers", "Montana State Bobcats", "Northwestern Wildcats", "Portland State Vikings", "Sam Houston State Bearkats", "Campbell Fighting Camels", "UC Davis Aggies", "Virginia Military Institute Keydets", "Monmouth Hawks", "Nicholls State Colonels", "Alcorn State Braves", "Virginia Cavaliers", "Georgia Bulldogs", "Missouri Tigers", "Houston Cougars", "Illinois State Redbirds", "Norfolk State Spartans", "Middle Tennessee Blue Raiders", "Abilene Christian Wildcats", "Louisiana Tech Bulldogs", "Houston Baptist Huskies", "Grambling State Tigers", "Weber State Wildcats", "Southern Utah Thunderbirds", "Fresno State Bulldogs", "Southern Methodist Mustangs", "UAB Blazers", "UCLA Bruins", "Miami (FL) Hurricanes", "Idaho Vandals"]

#     names = {}
#     missing_name_mapping.each do |name|
#       names[name] = action_names.select{|action| action.include?(name)}
#     end

#     final_names = {}
#     names.each do |k,v|
#       next if v.empty?
#       value = v.count == 1 ? v.first : v
#       final_names[k] = value
#     end
#   end
def pred_mapping
mapping = {"Navy"=>"Navy Midshipmen",
"Memphis"=>"Memphis Tigers",
"North Carolina A&T"=>"North Carolina A&T Aggies",
"San Diego St"=>"San Diego State Aztecs",
"Illinois"=>"Illinois Fighting Illini",
"Duke"=>"Duke Blue Devils",
"Colorado"=>"Colorado Buffaloes",
"Oregon"=>"Oregon Ducks",
"Virginia Tech"=>"Virginia Tech Hokies",
"Arizona St"=>"Arizona State Sun Devils",
"California"=>"California Bears",
"Penn St"=>"Penn State Nittany Lions",
"Maryland"=>"Maryland Terrapins",
"San Jose St"=>"San Jose State Spartans",
"Air Force"=>"Air Force Falcons",
"Rutgers"=>"Rutgers Scarlet Knights",
"Michigan"=>"Michigan Wolverines",
"N Illinois"=>"Northern Illinois Huskies",
"Vanderbilt"=>"Vanderbilt Commodores",
"Stanford"=>"Stanford Cardinal",
"Oregon St"=>"Oregon State Beavers",
"Iowa St"=>"Iowa State Cyclones",
"Baylor"=>"Baylor Bears",
"Louisiana"=>"Louisiana-Lafayette Ragin' Cajuns",
"Ga Southern"=>"Georgia Southern Eagles",
"Kentucky"=>"Kentucky Wildcats",
"South Carolina"=>"South Carolina Gamecocks",
"Texas Tech"=>"Texas Tech Red Raiders",
"Oklahoma"=>"Oklahoma Sooners",
"Ohio St"=>"Ohio State Buckeyes",
"Nebraska"=>"Nebraska Cornhuskers",
"Kansas"=>"Kansas Jayhawks",
"TCU"=>"TCU Horned Frogs",
"Northwestern"=>"Northwestern Wildcats",
"Wisconsin"=>"Wisconsin Badgers",
"FL Atlantic"=>"Florida Atlantic Owls",
"Charlotte"=>"Charlotte 49ers",
"SMU"=>"Southern Methodist Mustangs",
"South Florida"=>"South Florida Bulls",
"Coastal Car"=>"Coastal Carolina Chanticleers",
"Appalachian St"=>"Appalachian State Mountaineers",
"C Michigan"=>"Central Michigan Chippewas",
"W Michigan"=>"Western Michigan Broncos",
"Delaware"=>"Delaware Fightin Blue Hens",
"Pittsburgh"=>"Pittsburgh Panthers",
"Holy Cross"=>"Holy Cross Crusaders",
"Syracuse"=>"Syracuse Orange",
"Indiana"=>"Indiana Hoosiers",
"Michigan St"=>"Michigan State Spartans",
"Akron"=>"Akron Zips",
"Massachusetts"=>"Massachusetts Minutemen",
"Houston"=>"Houston Cougars",
"North Texas"=>"North Texas Mean Green",
"Buffalo"=>"Buffalo Bulls",
"Miami OH"=>"Miami (OH) RedHawks",
"Colorado St"=>"Colorado State Rams",
"Utah St"=>"Utah State Aggies",
"Minnesota"=>"Minnesota Golden Gophers",
"Purdue"=>"Purdue Boilermakers",
"South Alabama"=>"South Alabama Jaguars",
"ULM"=>"Louisiana-Monroe Warhawks",
"UAB"=>"UAB Blazers",
"WKU"=>"Western Kentucky Hilltoppers",
"Kansas St"=>"Kansas State Wildcats",
"Oklahoma St"=>"Oklahoma State Cowboys",
"Wake Forest"=>"Wake Forest Demon Deacons",
"Boston College"=>"Boston College Eagles",
"Fresno St"=>"Fresno State Bulldogs",
"New Mexico St"=>"New Mexico State Aggies",
"MTSU"=>"Middle Tennessee Blue Raiders",
"Iowa"=>"Iowa Hawkeyes",
"Louisiana Tech"=>"Louisiana Tech Bulldogs",
"Rice"=>"Rice Owls",
"NC State"=>"North Carolina State Wolfpack",
"Florida St"=>"Florida State Seminoles",
"Cincinnati"=>"Cincinnati Bearcats",
"Marshall"=>"Marshall Thundering Herd",
"New Mexico"=>"New Mexico Lobos",
"Liberty"=>"Liberty Flames",
"Connecticut"=>"Connecticut Huskies",
"UCF"=>"UCF Knights",
"Virginia"=>"Virginia Cavaliers",
"Notre Dame"=>"Notre Dame Fighting Irish",
"UNLV"=>"UNLV Rebels",
"Wyoming"=>"Wyoming Cowboys",
"Clemson"=>"Clemson Tigers",
"North Carolina"=>"North Carolina Tar Heels",
"Mississippi"=>"Mississippi State Bulldogs",
"Alabama"=>"Alabama Crimson Tide",
"UCLA"=>"UCLA Bruins",
"Kent"=>"Kent State Golden Flashes",
"Arizona"=>"Arizona Wildcats",
"Arkansas St"=>"Arkansas State Red Wolves",
"Troy"=>"Troy Trojans",
"Mississippi St"=>"Mississippi State Bulldogs",
"Auburn"=>"Auburn Tigers",
"East Carolina"=>"East Carolina Pirates",
"Old Dominion"=>"Old Dominion Monarchs",
"UTEP"=>"UTEP Miners",
"Southern Miss"=>"Southern Miss Golden Eagles",
"Georgia Tech"=>"Georgia Tech Yellow Jackets",
"Georgia"=>"Georgia Bulldogs",
"Temple"=>"Temple Owls",
"Towson"=>"Towson Tigers",
"Florida"=>"Florida Gators",
"USC"=>"USC Trojans",
"Miami FL"=>"Miami (FL) Hurricanes",
"Boise St"=>"Boise State Broncos",
"Washington"=>"Washington Huskies",
"BYU"=>"BYU Cougars",
"Toledo"=>"Toledo Rockets",
"Hawaii"=>"Hawaii Warriors",
"Nevada"=>"Nevada Wolf Pack",
"Nicholls St"=>"Nicholls State Colonels",
"Texas St"=>"Texas State Bobcats",
"Washington St"=>"Washington State Cougars",
"Utah"=>"Utah Utes",
"Texas A&M"=>"Texas A&M Aggies",
"Tulane"=>"Tulane Green Wave",
"E Michigan"=>"Eastern Michigan Eagles",
"Bowling Green"=>"Bowling Green Falcons",
"Florida Intl"=>"Florida International Golden Panthers",
"S Dakota St"=>"South Dakota State Jackrabbits",
"Wagner"=>"Wagner Seahawks",
"Morgan St"=>"Morgan State Bears",
"Robert Morris"=>"Robert Morris Colonials",
"Florida A&M"=>"Florida A&M Rattlers",
"Army"=>"Army Black Knights",
"Tulsa"=>"Tulsa Golden Hurricane",
"Grambling"=>"Grambling State Tigers",
"Illinois St"=>"Illinois State Redbirds",
"Incarnate Word"=>"Incarnate Word Cardinals",
"Weber St"=>"Weber State Wildcats",
"James Madison"=>"James Madison Dukes",
"West Virginia"=>"West Virginia Mountaineers",
"Texas"=>"Texas Longhorns",
"Howard"=>"Howard Bison",
"Houston Bap"=>"Houston Baptist Huskies",
"Abilene Chr"=>"Abilene Christian Wildcats",
"Idaho"=>"Idaho Vandals",
"Norfolk St"=>"Norfolk State Spartans",
"Colgate"=>"Colgate Raiders",
"Bucknell"=>"Bucknell Bison",
"Rhode Island"=>"Rhode Island Rams",
"Ohio"=>"Ohio State Buckeyes",
"Portland St"=>"Portland State Vikings",
"Northern Iowa"=>"Northern Iowa Panthers",
"Alcorn St"=>"Alcorn State Braves",
"Indiana St"=>"Indiana State Sycamores",
"Sam Houston St"=>"Sam Houston State Bearkats",
"Ball St"=>"Ball State Cardinals",
"Montana St"=>"Montana State Bobcats",
"Campbell"=>"Campbell Fighting Camels",
"LSU"=>"LSU Tigers",
"Georgia St"=>"Georgia State Panthers",
"Tennessee"=>"Tennessee Volunteers",
"Southern Utah"=>"Southern Utah Thunderbirds",
"UC Davis"=>"UC Davis Aggies",
"Missouri"=>"Missouri Tigers",
"Louisville"=>"Louisville Cardinals",
"Arkansas"=>"Arkansas Razorbacks"
}

pred = ["Air Force", "Arizona", "Arkansas St.", "Army", "Auburn", "Ball St.", "Baylor", "Boise St.", "Boston College", "Bowling Green", "Buffalo", "California", "Central Florida", "Central Mich.", "Cincinnati", "Colorado", "Colorado St.", "Connecticut", "Duke", "East Carolina", "Eastern Mich.", "Florida", "Florida Intl.", "Georgia", "Georgia Southern", "Georgia St.", "Georgia Tech", "Illinois", "Iowa", "Iowa St.", "Kansas", "Kansas St.", "Kent", "LSU", "Liberty", "Louisiana-Monroe", "Louisville", "Marshall", "Maryland", "Massachusetts", "Memphis", "Miami (Fla.)", "Michigan", "Michigan St.", "Middle Tenn.", "Minnesota", "Mississippi", "Missouri", "Navy", "Nebraska", "New Mexico", "New Mexico St.", "North Carolina", "Northern Ill.", "Northwestern", "Notre Dame", "Ohio", "Ohio St.", "Oklahoma", "Oklahoma St.", "Old Dominion", "Oregon", "Oregon St.", "Penn St.", "Pittsburgh", "Purdue", "Rice", "Rutgers", "SMU", "San Diego St.", "San Jose St.", "South Alabama", "South Florida", "Stanford", "TCU", "Temple", "Tennessee", "Texas", "Texas Tech", "Texas-San Antonio", "Toledo", "Troy St.", "Tulane", "Tulsa", "UAB", "UCLA", "UNLV", "UTEP", "Utah St.", "Vanderbilt", "Virginia Tech", "Washington", "West Va.", "Western Kentucky", "Western Mich.", "Wisconsin"]


match_hash = {}
pred.each do |name|
  match_hash[name] = mapping.select {|k,v| k.downcase.gsub('.','') == (name.downcase.gsub('.',''))}.values[0]
end
print match_hash
binding.pry

end