class Conversions::MapNcaafTeam < Less::Interaction
	expects :team_name

	def run
		format_name
	end

	private

  def format_name
    downcase_team_names = {}
    team_name_mapping.each do |k,v|
      downcase_team_names[k.downcase] = v.downcase
    end
    if downcase_team_names["#{team_name.downcase}"]
      downcase_team_names["#{team_name.downcase}"]
    else
      puts "Unable to find mapping for #{team_name}"
      team_name
    end

  end

  def team_name_mapping
    {"Navy"=>"Navy Midshipmen",
    "Memphis"=>"Memphis Tigers",
    "Duke"=>"Duke Blue Devils",
    "Virginia Tech"=>"Virginia Tech Hokies",
    "Arizona State"=>"Arizona State Sun Devils",
    "California"=>"California Bears",
    "Penn State"=>"Penn State Nittany Lions",
    "Maryland"=>"Maryland Terrapins",
    "San Jose State"=>"San Jose State Spartans",
    "Air Force"=>"Air Force Falcons",
    "Rutgers"=>"Rutgers Scarlet Knights",
    "Michigan"=>"Michigan Wolverines",
    "N. Illinois"=>"Northern Illinois Huskies",
    "Vanderbilt"=>"Vanderbilt Commodores",
    "Stateanford"=>"Stanford Cardinal",
    "Oregon State"=>"Oregon State Beavers",
    "Iowa State"=>"Iowa State Cyclones",
    "Baylor"=>"Baylor Bears",
    "Louisiana"=>"Louisiana-Lafayette Ragin' Cajuns",
    "Ga Southern"=>"Georgia Southern Eagles",
    "Kentucky"=>"Kentucky Wildcats",
    "South Carolina"=>"South Carolina Gamecocks",
    "Texas Tech"=>"Texas Tech Red Raiders",
    "Oklahoma"=>"Oklahoma Sooners",
    "Ohio State"=>"Ohio State Buckeyes",
    "Nebraska"=>"Nebraska Cornhuskers",
    "Kansas"=>"Kansas Jayhawks",
    "TCU"=>"TCU Horned Frogs",
    "Northwestern"=>"Northwestern Wildcats",
    "Wisconsin"=>"Wisconsin Badgers",
    "FL Atlantic"=>"Florida Atlantic Owls",
    "Charlotte"=>"Charlotte 49ers",
    "SMU"=>"Southern Methodist Mustangs",
    "South Florida"=>"South Florida Bulls",
    "Coastal Car"=>"Coastal Carolina Chanticleers",
    "Appalachian State"=>"Appalachian State Mountaineers",
    "Central Michigan"=>"Central Michigan Chippewas",
    "W. Michigan"=>"Western Michigan Broncos",
    "Delaware"=>"Delaware Fightin Blue Hens",
    "Pittsburgh"=>"Pittsburgh Panthers",
    "Holy Cross"=>"Holy Cross Crusaders",
    "Syracuse"=>"Syracuse Orange",
    "Indiana"=>"Indiana Hoosiers",
    "Michigan State"=>"Michigan State Spartans",
    "Akron"=>"Akron Zips",
    "Massachusetts"=>"Massachusetts Minutemen",
    "Houston"=>"Houston Cougars",
    "North Texas"=>"North Texas Mean Green",
    "Buffalo"=>"Buffalo Bulls",
    "Miami (Ohio)"=>"Miami (OH) RedHawks",
    "Colorado State"=>"Colorado State Rams",
    "Utah State"=>"Utah State Aggies",
    "Minnesota"=>"Minnesota Golden Gophers",
    "Purdue"=>"Purdue Boilermakers",
    "South Alabama"=>"South Alabama Jaguars",
    "ULM"=>"Louisiana-Monroe Warhawks",
    "UAB"=>"UAB Blazers",
    "WKU"=>"Western Kentucky Hilltoppers",
    "Kansas State"=> "Kansas State Wildcats",
    "Oklahoma State"=>"Oklahoma State Cowboys",
    "Wake Forest"=>"Wake Forest Demon Deacons",
    "Boston College"=>"Boston College Eagles",
    "Fresno State"=>"Fresno State Bulldogs",
    "New Mexico State"=>"New Mexico State Aggies",
    "MTSU"=>"Middle Tennessee Blue Raiders",
    "Iowa"=>"Iowa Hawkeyes",
    "Louisiana Tech"=>"Louisiana Tech Bulldogs",
    "Rice"=>"Rice Owls",
    "NC Stateate"=>"North Carolina State Wolfpack",
    "Florida State"=>"Florida State Seminoles",
    "Cincinnati"=>"Cincinnati Bearcats",
    "Marshall"=>"Marshall Thundering Herd",
    "New Mexico"=>"New Mexico Lobos",
    "Liberty"=>"Liberty Flames",
    "Connecticut"=>"Connecticut Huskies",
    "UCF"=>"UCF Knights",
    "Virginia"=>"Virginia Cavaliers",
    "Notre Dame"=>"Notre Dame Fighting Irish",
    "UNLV"=>"UNLV Rebels",
    "Wyoming"=>"Wyoming Cowboys",
    "Clemson"=>"Clemson Tigers",
    "North Carolina"=>"North Carolina Tar Heels",
    "Mississippi"=>"Mississippi State Bulldogs",
    "Alabama"=>"Alabama Crimson Tide",
    "UCLA"=>"UCLA Bruins",
    "Arizona"=> "Arizona Wildcats",
    "Arkansas State"=>"Arkansas State Red Wolves",
    "Troy"=>"Troy Trojans",
    "Mississippi State"=>"Mississippi State Bulldogs",
    "Auburn"=>"Auburn Tigers",
    "East Carolina"=>"East Carolina Pirates",
    "Old Dominion"=>"Old Dominion Monarchs",
    "UTEP"=>"UTEP Miners",
    "Southern Miss."=>"Southern Miss Golden Eagles",
    "Georgia Tech"=>"Georgia Tech Yellow Jackets",
    "Temple"=>"Temple Owls",
    "Towson"=>"Towson Tigers",
    "Florida"=>"Florida Gators",
    "USC"=>"USC Trojans",
    "Washington"=>"Washington Huskies",
    "BYU"=>"BYU Cougars",
    "Toledo"=>"Toledo Rockets",
    "Hawaii"=>"Hawaii Warriors",
    "Nevada"=>"Nevada Wolf Pack",
    "Nicholls State"=>"Nicholls State Colonels",
    "Texas State"=>"Texas State Bobcats",
    "Washington State"=>"Washington State Cougars",
    "Utah"=> "Utah Utes",
    "Texas A&M"=>"Texas A&M Aggies",
    "Arkansas"=>"Arkansas Razorbacks"}
  end
	def old_team_mapping
    {
     "utah"=>"utah utes",
     "e. michigan"=>"eastern michigan eagles",
     "w. michigan"=>"western michigan broncos",
     "duke"=>"duke blue devils",
     "tulane"=>"tulane green wave",
     "minnesota"=>"minnesota golden gophers",
     "san jose st."=>"san jose state spartans",
     "michigan st."=>"michigan state spartans",
     "ball st."=>"ball state cardinals",
     "purdue"=>"purdue boilermakers",
     "wisconsin"=>"wisconsin badgers",
     "connecticut"=>"connecticut huskies",
     "smu"=>"Southern Methodist Mustangs",
     "syracuse"=>"syracuse orange",
     "utah st."=>"utah state aggies",
     "wake forest"=>"wake forest demon deacons",
     "weber st."=>"weber state wildcats",
     "army"=>"army black knights",
     "uc davis"=>"uc davis aggies",
     "northwestern"=>"northwestern wildcats",
     "se. louisiana"=>"southeastern louisiana lions",
     "monmouth nj"=>"monmouth hawks",
     "ucf"=>"ucf knights",
     "central conn"=>"central connecticut state blue devils",
     "wku"=>"western kentucky hilltoppers",
     "vanderbilt"=>"vanderbilt commodores",
     "alabama"=>"alabama crimson tide",
     "pittsburgh"=>"pittsburgh panthers",
     "liberty"=>"liberty flames",
     "virginia"=>"virginia cavaliers",
     "louisiana-monroe"=>"louisiana-monroe warhawks",
     "maryland"=>"maryland terrapins",
     "arkansas st."=>"arkansas state red wolves",
     "notre dame"=>"notre dame fighting irish",
     "rice"=>"rice owls",
     "lsu"=>"lsu tigers",
     "california"=>"california bears",
     "massachusetts"=>"massachusetts minutemen",
     "oregon"=>"oregon ducks",
     "temple"=>"temple owls",
     "south carolina"=>"south carolina gamecocks",
     "kansas"=>"kansas jayhawks",
     "texas tech"=>"texas tech red raiders",
     "fresno st."=>"fresno state bulldogs",
     "tennessee"=>"tennessee volunteers",
     "miami (ohio)"=>"miami (oh) redhawks",
     "usc"=>"usc trojans",
     "east carolina"=>"east carolina pirates",
     "auburn"=>"auburn tigers",
     "tulsa"=>"tulsa golden hurricane",
     "memphis"=>"memphis tigers",
     "boston college"=>"boston college eagles",
     "ucla"=>"ucla bruins",
     "south florida"=>"south florida bulls",
     "florida intl"=>"florida international golden panthers",
     "kentucky"=>"kentucky wildcats",
     "nebraska"=>"nebraska cornhuskers",
     "ohio st."=>"ohio state buckeyes",
     "new mexico"=>"new mexico lobos",
     "hawaii"=>"hawaii warriors",
     "charlotte"=>"charlotte 49ers",
     "arizona"=>"arizona wildcats",
     "oklahoma"=>"oklahoma sooners",
     "north texas"=>"north texas mean green",
     "florida st."=>"florida state seminoles",
     "north carolina st."=>"north carolina state wolfpack",
     "south alabama"=>"south alabama jaguars",
     "kansas st."=>"kansas state wildcats",
     "illinois"=>"illinois fighting illini",
     "colorado st."=>"colorado state rams",
     "stanford"=>"stanford cardinal",
     "rutgers"=>"rutgers scarlet knights",
     "iowa"=>"iowa hawkeyes",
     "penn st."=>"penn state nittany lions",
     "nevada"=>"nevada wolf pack",
     "wyoming"=>"wyoming cowboys",
     "arizona st."=>"arizona state sun devils",
     "new mexico st."=>"new mexico state aggies",
     "air force"=>"air force falcons",
     "troy"=>"troy trojans",
     "iowa st."=>"iowa state cyclones",
     "kent"=>"kent state golden flashes",
     "washington"=>"washington huskies",
     "appalachian st."=>"appalachian state mountaineers",
     "texas"=>"texas longhorns",
     "bowling green"=>"bowling green falcons",
     "michigan"=>"michigan wolverines",
     "colorado"=>"colorado buffaloes",
     "houston"=>"houston cougars",
     "akron"=>"akron zips",
     "villanova"=>"villanova wildcats",
     "san diego st."=>"san diego state aztecs",
     "navy"=>"navy midshipmen",
     "mercer"=>"mercer bears",
     "florida atlantic"=>"florida atlantic owls",
     "unlv"=>"unlv rebels",
     "texas state"=>"texas state bobcats",
     "south carolina st."=>"south carolina state bulldogs",
     "coastal car"=>"coastal carolina chanticleers",
     "fordham"=>"fordham rams",
     "byu"=>"byu cougars",
     "north carolina a&t"=>"north carolina a&t aggies",
     "incarnate word"=>"incarnate word cardinals",
     "marshall"=>"marshall thundering herd",
     "washington st."=>"washington state cougars",
     "james madison"=>"james madison dukes",
     "n. illinois"=>"northern illinois huskies",
     "albany"=>"albany great danes",
     "louisiana tech"=>"louisiana tech bulldogs",
     "middle tennessee"=>"middle tennessee blue raiders",
     "south dakota"=>"south dakota coyotes",
     "elon"=>"elon phoenix",
     "louisville"=>"louisville cardinals",
     "duquesne"=>"duquesne dukes",
     "cincinnati"=>"cincinnati bearcats",
     "ole miss"=>"ole miss rebels",
     "central michigan"=>"central michigan chippewas",
     "stony brook"=>"stony brook seawolves",
     "virginia tech"=>"virginia tech hokies",
     "west virginia"=>"west virginia mountaineers",
     "north carolina"=>"north carolina tar heels",
     "south dakota st."=>"south dakota state jackrabbits",
     "miami"=>"miami (fl) hurricanes",
     "old dominion"=>"old dominion monarchs",
     "s. methodist"=>"southern methodist mustangs",
     "prairie view a&m"=>"prairie view a&m panthers",
     "oregon st."=>"oregon state beavers",
     "nicholls st."=>"nicholls state colonels",
     "idaho"=>"idaho vandals",
     "boise st."=>"boise state broncos",
     "indiana"=>"indiana hoosiers"
    }
	end
end
