class Conversions::MapNcaafTeam < Less::Interaction
	expects :team_name

	def run
		get_pregame_name
	end

	private

	def get_pregame_name
    teams["#{team_name.downcase}"] || team_name
	end

	def teams
    {
     "utah"=>"utah utes",
     "e. michigan"=>"eastern michigan eagles",
     "w. michigan"=>"western michigan broncos",
     "duke"=>"duke blue devils",
     "tulane"=>"tulane green wave",
     "minnesota"=>"minnesota golden gophers",
     "san jose st."=>"san jose state spartans",
     "michigan st."=>"michigan state spartans",
     "ball st."=>"ball state cardinals",
     "purdue"=>"purdue boilermakers",
     "wisconsin"=>"wisconsin badgers",
     "connecticut"=>"connecticut huskies",
     "syracuse"=>"syracuse orange",
     "utah st."=>"utah state aggies",
     "wake forest"=>"wake forest demon deacons",
     "weber st."=>"weber state wildcats",
     "army"=>"army black knights",
     "uc davis"=>"uc davis aggies",
     "northwestern"=>"northwestern wildcats",
     "se. louisiana"=>"southeastern louisiana lions",
     "monmouth nj"=>"monmouth hawks",
     "ucf"=>"ucf knights",
     "central conn"=>"central connecticut state blue devils",
     "wku"=>"western kentucky hilltoppers",
     "vanderbilt"=>"vanderbilt commodores",
     "alabama"=>"alabama crimson tide",
     "pittsburgh"=>"pittsburgh panthers",
     "liberty"=>"liberty flames",
     "virginia"=>"virginia cavaliers",
     "louisiana-monroe"=>"louisiana-monroe warhawks",
     "maryland"=>"maryland terrapins",
     "arkansas st."=>"arkansas state red wolves",
     "notre dame"=>"notre dame fighting irish",
     "rice"=>"rice owls",
     "lsu"=>"lsu tigers",
     "california"=>"california bears",
     "massachusetts"=>"massachusetts minutemen",
     "oregon"=>"oregon ducks",
     "temple"=>"temple owls",
     "south carolina"=>"south carolina gamecocks",
     "kansas"=>"kansas jayhawks",
     "texas tech"=>"texas tech red raiders",
     "fresno st."=>"fresno state bulldogs",
     "tennessee"=>"tennessee volunteers",
     "miami (ohio)"=>"miami (oh) redhawks",
     "usc"=>"usc trojans",
     "east carolina"=>"east carolina pirates",
     "auburn"=>"auburn tigers",
     "tulsa"=>"tulsa golden hurricane",
     "memphis"=>"memphis tigers",
     "boston college"=>"boston college eagles",
     "ucla"=>"ucla bruins",
     "south florida"=>"south florida bulls",
     "florida intl"=>"florida international golden panthers",
     "kentucky"=>"kentucky wildcats",
     "nebraska"=>"nebraska cornhuskers",
     "ohio st."=>"ohio state buckeyes",
     "new mexico"=>"new mexico lobos",
     "hawaii"=>"hawaii warriors",
     "charlotte"=>"charlotte 49ers",
     "arizona"=>"arizona wildcats",
     "oklahoma"=>"oklahoma sooners",
     "north texas"=>"north texas mean green",
     "florida st."=>"florida state seminoles",
     "north carolina st."=>"north carolina state wolfpack",
     "south alabama"=>"south alabama jaguars",
     "kansas st."=>"kansas state wildcats",
     "illinois"=>"illinois fighting illini",
     "colorado st."=>"colorado state rams",
     "stanford"=>"stanford cardinal",
     "rutgers"=>"rutgers scarlet knights",
     "iowa"=>"iowa hawkeyes",
     "penn st."=>"penn state nittany lions",
     "nevada"=>"nevada wolf pack",
     "wyoming"=>"wyoming cowboys",
     "arizona st."=>"arizona state sun devils",
     "new mexico st."=>"new mexico state aggies",
     "air force"=>"air force falcons",
     "troy"=>"troy trojans",
     "iowa st."=>"iowa state cyclones",
     "kent"=>"kent state golden flashes",
     "washington"=>"washington huskies",
     "appalachian st."=>"appalachian state mountaineers",
     "texas"=>"texas longhorns",
     "bowling green"=>"bowling green falcons",
     "michigan"=>"michigan wolverines",
     "colorado"=>"colorado buffaloes",
     "houston"=>"houston cougars",
     "akron"=>"akron zips",
     "villanova"=>"villanova wildcats",
     "san diego st."=>"san diego state aztecs",
     "navy"=>"navy midshipmen",
     "mercer"=>"mercer bears",
     "florida atlantic"=>"florida atlantic owls",
     "unlv"=>"unlv rebels",
     "texas state"=>"texas state bobcats",
     "south carolina st."=>"south carolina state bulldogs",
     "coastal car"=>"coastal carolina chanticleers",
     "fordham"=>"fordham rams",
     "byu"=>"byu cougars",
     "north carolina a&t"=>"north carolina a&t aggies",
     "incarnate word"=>"incarnate word cardinals",
     "marshall"=>"marshall thundering herd",
     "washington st."=>"washington state cougars",
     "james madison"=>"james madison dukes",
     "n. illinois"=>"northern illinois huskies",
     "albany"=>"albany great danes",
     "louisiana tech"=>"louisiana tech bulldogs",
     "middle tennessee"=>"middle tennessee blue raiders",
     "south dakota"=>"south dakota coyotes",
     "elon"=>"elon phoenix",
     "louisville"=>"louisville cardinals",
     "duquesne"=>"duquesne dukes",
     "cincinnati"=>"cincinnati bearcats",
     "ole miss"=>"ole miss rebels",
     "central michigan"=>"central michigan chippewas",
     "stony brook"=>"stony brook seawolves",
     "virginia tech"=>"virginia tech hokies",
     "west virginia"=>"west virginia mountaineers",
     "north carolina"=>"north carolina tar heels",
     "south dakota st."=>"south dakota state jackrabbits",
     "miami"=>"miami (fl) hurricanes",
     "old dominion"=>"old dominion monarchs",
     "s. methodist"=>"southern methodist mustangs",
     "prairie view a&m"=>"prairie view a&m panthers",
     "oregon st."=>"oregon state beavers",
     "nicholls st."=>"nicholls state colonels",
     "idaho"=>"idaho vandals",
     "boise st."=>"boise state broncos",
     "indiana"=>"indiana hoosiers"
    }
	end
end
